# Generated by Django 6.0.6 on 2026-06-07 17:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الساعة (ترجمة فورية)')),
                ('page_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الصفحة (ترجمة تحريرية)')),
            ],
            options={
                'verbose_name': 'اللغة',
                'verbose_name_plural': 'اللغات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Prosecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم النيابة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الرمز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'النيابة',
                'verbose_name_plural': 'النيابات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prosecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المحقق')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('prosecution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosecutors', to='core.prosecution', verbose_name='النيابة')),
            ],
            options={
                'verbose_name': 'المحقق',
                'verbose_name_plural': 'المحققون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PP_STAFF', 'موظف النيابة'), ('SMARTWORLD_ADMIN', 'مدير سمارت وورلد'), ('SMARTWORLD_STAFF', 'موظف سمارت وورلد'), ('CONTRACT_MANAGER', 'مدير العقد')], max_length=20, verbose_name='الدور')),
                ('prosecution', models.ForeignKey(blank=True, help_text='فقط لموظفي النيابة', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prosecution', verbose_name='النيابة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم أمر التكليف')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('service_type', models.CharField(choices=[('INTERPRETATION', 'ترجمة فورية'), ('WRITTEN', 'ترجمة تحريرية'), ('REVIEW', 'مراجعة'), ('AI_REVIEW', 'مراجعة بالذكاء الاصطناعي')], max_length=20, verbose_name='نوع الخدمة')),
                ('execution_date', models.DateField(verbose_name='تاريخ التنفيذ')),
                ('execution_time', models.TimeField(verbose_name='وقت التنفيذ')),
                ('estimated_duration', models.DecimalField(blank=True, choices=[(Decimal('0.5'), 'نصف ساعة'), (Decimal('1'), 'ساعة واحدة'), (Decimal('1.5'), 'ساعة ونصف'), (Decimal('2'), 'ساعتان'), (Decimal('3'), '3 ساعات'), (Decimal('4'), '4 ساعات'), (Decimal('5'), '5 ساعات'), (Decimal('6'), '6 ساعات'), (Decimal('8'), '8 ساعات')], decimal_places=1, max_digits=4, null=True, verbose_name='المدة التقديرية (ساعات)')),
                ('location_type', models.CharField(choices=[('ONSITE', 'حضوري'), ('ONLINE', 'عن بعد (رابط متوفر)'), ('NEED_LINK', 'عن بعد (يرجى توفير الرابط)')], max_length=20, verbose_name='نوع الموقع')),
                ('location_detail', models.TextField(blank=True, help_text='العنوان أو رابط الاجتماع', verbose_name='تفاصيل الموقع')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='اسم جهة الاتصال')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف جهة الاتصال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('ACCEPTED', 'مقبول'), ('IN_PROGRESS', 'قيد التنفيذ'), ('PENDING_APPROVAL', 'بانتظار الاعتماد'), ('COMPLETED', 'مكتمل'), ('DISPUTED', 'متنازع عليه')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('prosecution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.prosecution', verbose_name='النيابة')),
                ('prosecutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.prosecutor', verbose_name='المحقق')),
            ],
            options={
                'verbose_name': 'أمر تكليف',
                'verbose_name_plural': 'أوامر التكليف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_translators', models.PositiveIntegerField(default=1, verbose_name='عدد المترجمين')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الساعات الفعلية')),
                ('actual_pages', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الصفحات الفعلية')),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.language', verbose_name='اللغة')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='core.workorder', verbose_name='أمر التكليف')),
            ],
            options={
                'verbose_name': 'سجل الخدمة',
                'verbose_name_plural': 'سجلات الخدمة',
            },
        ),
        migrations.CreateModel(
            name='CompletionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='رقم الشهادة')),
                ('certificate_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الشهادة')),
                ('invoice_number', models.CharField(blank=True, max_length=30, verbose_name='رقم الفاتورة')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الفاتورة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المجموع الفرعي')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='نسبة الضريبة')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ الضريبة')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المجموع الكلي')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('FINALIZED', 'نهائي')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='core.workorder', verbose_name='أمر التكليف')),
            ],
            options={
                'verbose_name': 'شهادة إنجاز',
                'verbose_name_plural': 'شهادات الإنجاز',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartworld_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اعتماد سمارت وورلد')),
                ('pp_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اعتماد النيابة')),
                ('pp_dispute_reason', models.TextField(blank=True, verbose_name='سبب الاعتراض')),
                ('pp_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_approvals', to=settings.AUTH_USER_MODEL, verbose_name='اعتماد النيابة')),
                ('smartworld_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_approvals', to=settings.AUTH_USER_MODEL, verbose_name='اعتماد سمارت وورلد')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='core.workorder', verbose_name='أمر التكليف')),
            ],
            options={
                'verbose_name': 'اعتماد أمر التكليف',
                'verbose_name_plural': 'اعتمادات أوامر التكليف',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_translators', models.PositiveIntegerField(default=1, verbose_name='عدد المترجمين')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الساعات التقديرية')),
                ('estimated_pages', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الصفحات التقديرية')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.language', verbose_name='اللغة')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='core.workorder', verbose_name='أمر التكليف')),
            ],
            options={
                'verbose_name': 'لغة أمر التكليف',
                'verbose_name_plural': 'لغات أمر التكليف',
            },
        ),
    ]
