# Generated by Django 6.0.6 on 2026-06-07 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='custom_prosecutor_name',
            field=models.CharField(blank=True, help_text='في حال عدم وجود المحقق في القائمة', max_length=200, verbose_name='اسم المحقق (يدوي)'),
        ),
        migrations.AddField(
            model_name='workorderlanguage',
            name='custom_language_name',
            field=models.CharField(blank=True, help_text='في حال اختيار "أخرى"', max_length=200, verbose_name='اسم اللغة (يدوي)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='prosecutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.prosecutor', verbose_name='المحقق'),
        ),
    ]
