# Generated by Django 6.0.6 on 2026-06-08 00:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workorder_custom_prosecutor_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('MANUAL', 'يدوي (مدير العقد يعين المترجمين)'), ('AUTO', 'تلقائي (المترجمون يختارون الأوامر)')], default='MANUAL', max_length=10, verbose_name='وضع سير العمل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات سير العمل',
                'verbose_name_plural': 'إعدادات سير العمل',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PP_STAFF', 'موظف النيابة'), ('SMARTWORLD_ADMIN', 'مدير سمارت وورلد'), ('SMARTWORLD_STAFF', 'موظف سمارت وورلد'), ('CONTRACT_MANAGER', 'مدير العقد'), ('TRANSLATOR', 'مترجم')], max_length=20, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='estimated_duration',
            field=models.DecimalField(blank=True, choices=[(Decimal('1'), 'ساعة واحدة'), (Decimal('2'), 'ساعتان'), (Decimal('3'), '3 ساعات'), (Decimal('4'), '4 ساعات'), (Decimal('5'), '5 ساعات'), (Decimal('6'), '6 ساعات'), (Decimal('8'), '8 ساعات')], decimal_places=1, max_digits=4, null=True, verbose_name='المدة التقديرية (ساعات)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('ACCEPTED', 'مقبول'), ('ASSIGNED', 'تم التعيين'), ('IN_PROGRESS', 'قيد التنفيذ'), ('PENDING_APPROVAL', 'بانتظار الاعتماد'), ('COMPLETED', 'مكتمل'), ('DISPUTED', 'متنازع عليه')], default='DRAFT', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار القبول'), ('ACCEPTED', 'مقبول'), ('DECLINED', 'مرفوض'), ('COMPLETED', 'مكتمل')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبول')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('language_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.workorderlanguage', verbose_name='بند اللغة')),
                ('service_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='core.servicerecord', verbose_name='سجل الخدمة')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='المترجم')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.workorder', verbose_name='أمر التكليف')),
            ],
            options={
                'verbose_name': 'تعيين مترجم',
                'verbose_name_plural': 'تعيينات المترجمين',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_interpret', models.BooleanField(default=True, verbose_name='ترجمة فورية')),
                ('can_translate', models.BooleanField(default=True, verbose_name='ترجمة تحريرية')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('languages', models.ManyToManyField(to='core.language', verbose_name='اللغات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translator_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مترجم',
                'verbose_name_plural': 'ملفات المترجمين',
            },
        ),
    ]
