# Generated by Django 6.0.6 on 2026-06-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workflowconfig_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='conference_room',
            field=models.CharField(blank=True, help_text='LiveKit room name (auto-generated)', max_length=100, verbose_name='غرفة الاجتماع'),
        ),
    ]
