# Generated by Django 6.0.6 on 2026-06-08 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_conference_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egress_id', models.CharField(max_length=100, unique=True, verbose_name='معرف التسجيل')),
                ('room_name', models.CharField(max_length=100, verbose_name='اسم الغرفة')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='مسار الملف')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='حجم الملف')),
                ('status', models.CharField(choices=[('RECORDING', 'جاري التسجيل'), ('STOPPING', 'جاري الإيقاف'), ('COMPLETED', 'مكتمل'), ('FAILED', 'فشل')], default='RECORDING', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإيقاف')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بدأ بواسطة')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.workorder', verbose_name='أمر التكليف')),
            ],
            options={
                'verbose_name': 'تسجيل اجتماع',
                'verbose_name_plural': 'تسجيلات الاجتماعات',
                'ordering': ['-started_at'],
            },
        ),
    ]
