# Generated by Django 5.2.17 on 2026-09-14 11:05

import core.models
import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conferencerecording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SOURCE', 'مستند للترجمة'), ('TRANSLATION', 'ترجمة منجزة')], max_length=20, verbose_name='النوع')),
                ('file', models.FileField(max_length=255, storage=core.storage.get_document_storage, upload_to=core.models.order_document_path, verbose_name='الملف')),
                ('original_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('size', models.PositiveBigIntegerField(verbose_name='الحجم')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع المحتوى')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('scan_status', models.CharField(choices=[('CLEAN', 'سليم'), ('NOT_SCANNED', 'غير مفحوص')], default='NOT_SCANNED', max_length=20, verbose_name='نتيجة الفحص')),
                ('purged_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف (سياسة الاحتفاظ)')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.orderassignment', verbose_name='التعيين')),
                ('language_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.workorderlanguage', verbose_name='بند اللغة')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.workorder', verbose_name='أمر التكليف')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ['-uploaded_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='الملاحظة')),
                ('status', models.CharField(choices=[('OPEN', 'بحاجة لمعالجة'), ('ADDRESSED', 'تمت المعالجة')], default='OPEN', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('addressed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('addressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='عولجت بواسطة')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_notes', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('language_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_notes', to='core.workorderlanguage', verbose_name='بند اللغة')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_notes', to='core.workorder', verbose_name='أمر التكليف')),
                ('addressed_by_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressed_notes', to='core.orderdocument', verbose_name='النسخة المعدلة')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_notes', to='core.orderdocument', verbose_name='الملف المعني')),
            ],
            options={
                'verbose_name': 'ملاحظة مراجعة',
                'verbose_name_plural': 'ملاحظات المراجعة',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
