# Generated by Django 5.2.17 on 2026-09-14 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_orderdocument_documentnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مجال قانوني',
                'verbose_name_plural': 'المجالات القانونية',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_ar', models.CharField(max_length=500, verbose_name='المصطلح بالعربية')),
                ('term_en', models.CharField(max_length=500, verbose_name='المصطلح بالإنجليزية')),
                ('term_ar_normalized', models.CharField(db_index=True, editable=False, max_length=500)),
                ('term_en_normalized', models.CharField(db_index=True, editable=False, max_length=500)),
                ('search_text', models.TextField(default='', editable=False)),
                ('part_of_speech', models.CharField(blank=True, choices=[('NOUN', 'اسم'), ('VERB', 'فعل'), ('ADJECTIVE', 'صفة'), ('PHRASE', 'عبارة'), ('ABBREVIATION', 'اختصار')], max_length=20, verbose_name='نوع الكلمة')),
                ('definition_ar', models.TextField(blank=True, verbose_name='التعريف بالعربية')),
                ('definition_en', models.TextField(blank=True, verbose_name='التعريف بالإنجليزية')),
                ('example_ar', models.TextField(blank=True, verbose_name='مثال بالعربية')),
                ('example_en', models.TextField(blank=True, verbose_name='مثال بالإنجليزية')),
                ('source_reference', models.CharField(blank=True, help_text='مثال: قانون الإجراءات الجزائية الاتحادي، المادة 5', max_length=500, verbose_name='المرجع القانوني')),
                ('synonyms_ar', models.TextField(blank=True, help_text='صيغة واحدة في كل سطر', verbose_name='مرادفات عربية مقبولة')),
                ('synonyms_en', models.TextField(blank=True, help_text='صيغة واحدة في كل سطر', verbose_name='مرادفات إنجليزية مقبولة')),
                ('forbidden_ar', models.TextField(blank=True, help_text='صيغة واحدة في كل سطر', verbose_name='صيغ عربية غير مقبولة')),
                ('forbidden_en', models.TextField(blank=True, help_text='صيغة واحدة في كل سطر', verbose_name='صيغ إنجليزية غير مقبولة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('PROPOSED', 'مقترح'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض')], default='PROPOSED', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_note', models.TextField(blank=True, verbose_name='ملاحظة المراجعة')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_glossary_terms', to=settings.AUTH_USER_MODEL, verbose_name='اقترحه')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='راجعه')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to='glossary.legaldomain', verbose_name='المجال القانوني')),
            ],
            options={
                'verbose_name': 'مصطلح',
                'verbose_name_plural': 'المصطلحات',
                'ordering': ['term_ar_normalized'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTermHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'إنشاء'), ('UPDATED', 'تعديل'), ('APPROVED', 'اعتماد'), ('REJECTED', 'رفض'), ('ARCHIVED', 'أرشفة'), ('RESTORED', 'استعادة'), ('IMPORTED', 'استيراد')], max_length=20, verbose_name='الإجراء')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='glossary.glossaryterm', verbose_name='المصطلح')),
            ],
            options={
                'verbose_name': 'سجل تغيير',
                'verbose_name_plural': 'سجل التغييرات',
                'ordering': ['-changed_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='ملاحظة')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أضافه')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_links', to='glossary.glossaryterm', verbose_name='المصطلح')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='core.workorder', verbose_name='أمر التكليف')),
            ],
            options={
                'verbose_name': 'مصطلح أمر التكليف',
                'verbose_name_plural': 'مصطلحات أوامر التكليف',
                'ordering': ['term__term_ar_normalized'],
            },
        ),
        migrations.AddConstraint(
            model_name='glossaryterm',
            constraint=models.UniqueConstraint(fields=('term_ar_normalized', 'term_en_normalized'), name='glossary_unique_normalized_pair'),
        ),
        migrations.AddConstraint(
            model_name='orderterm',
            constraint=models.UniqueConstraint(fields=('work_order', 'term'), name='glossary_unique_order_term'),
        ),
    ]
